/**
 * Constantes de la aplicación
 * Centraliza IDs de colecciones y configuración de Appwrite
 */

// Environment variables
const envVar = (key, fallback = "") => import.meta.env[key] || fallback;

// Appwrite Configuration
export const APPWRITE = {
  endpoint: envVar("VITE_APPWRITE_ENDPOINT"),
  projectId: envVar("VITE_APPWRITE_PROJECT_ID"),
  databaseId: envVar("VITE_APPWRITE_DATABASE_ID"),
};

// Collection IDs
export const COLLECTIONS = {
  USERS_PROFILE: envVar("VITE_APPWRITE_COLLECTION_USERS_PROFILE_ID"),
  GROUPS: envVar("VITE_APPWRITE_COLLECTION_GROUPS_ID"),
  GROUP_MEMBERS: envVar("VITE_APPWRITE_COLLECTION_GROUP_MEMBERS_ID"),
  GROUP_INVITATIONS: envVar("VITE_APPWRITE_COLLECTION_GROUP_INVITATIONS_ID"),
  PERMISSIONS: envVar("VITE_APPWRITE_COLLECTION_PERMISSIONS_ID"),
  ROLES: envVar("VITE_APPWRITE_COLLECTION_ROLES_ID"),
  ROLE_PERMISSIONS: envVar("VITE_APPWRITE_COLLECTION_ROLE_PERMISSIONS_ID"),
  USER_ROLES: envVar("VITE_APPWRITE_COLLECTION_USER_ROLES_ID"),
  CALENDARS: envVar("VITE_APPWRITE_COLLECTION_CALENDARS_ID"),
  EVENTS: envVar("VITE_APPWRITE_COLLECTION_EVENTS_ID"),
  EVENT_ATTENDEES: envVar("VITE_APPWRITE_COLLECTION_EVENT_ATTENDEES_ID"),
  EVENT_REMINDERS: envVar("VITE_APPWRITE_COLLECTION_EVENT_REMINDERS_ID"),
  NOTIFICATIONS: envVar("VITE_APPWRITE_COLLECTION_NOTIFICATIONS_ID"),
  USER_SETTINGS: envVar("VITE_APPWRITE_COLLECTION_USER_SETTINGS_ID"),
  PUSH_SUBSCRIPTIONS: envVar("VITE_APPWRITE_COLLECTION_PUSH_SUBSCRIPTIONS_ID"),
  AUDIT_LOGS: envVar("VITE_APPWRITE_COLLECTION_AUDIT_LOGS_ID"),
};

// Bucket IDs
export const BUCKETS = {
  AVATARS: envVar("VITE_APPWRITE_BUCKET_AVATARS_ID"),
  ATTACHMENTS: envVar("VITE_APPWRITE_BUCKET_ATTACHMENTS_ID"),
};

// Function IDs
export const FUNCTIONS = {
  CREATE_USER_WITH_PROFILE: envVar(
    "VITE_APPWRITE_FN_CREATE_USER_WITH_PROFILE_ID"
  ),
  ENSURE_PROFILE: envVar("VITE_APPWRITE_FN_ENSURE_PROFILE_ID"),
  CREATE_GROUP_WITH_DEFAULTS: envVar(
    "VITE_APPWRITE_FN_CREATE_GROUP_WITH_DEFAULTS_ID"
  ),
  INVITE_TO_GROUP: envVar("VITE_APPWRITE_FN_INVITE_TO_GROUP_ID"),
  ACCEPT_INVITATION: envVar("VITE_APPWRITE_FN_ACCEPT_INVITATION_ID"),
};

// Enums matching database schema
export const ENUMS = {
  USER_STATUS: {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    DELETED: "DELETED",
  },
  GROUP_MEMBER_ROLE: {
    OWNER: "OWNER",
    MEMBER: "MEMBER",
  },
  INVITATION_STATUS: {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
    EXPIRED: "EXPIRED",
    CANCELLED: "CANCELLED",
  },
  CALENDAR_VISIBILITY: {
    PRIVATE: "PRIVATE",
    GROUP: "GROUP",
  },
  EVENT_STATUS: {
    DRAFT: "DRAFT",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
  },
  EVENT_VISIBILITY: {
    INHERIT: "INHERIT",
    PRIVATE: "PRIVATE",
    GROUP: "GROUP",
  },
  ATTENDEE_ROLE: {
    REQUIRED: "REQUIRED",
    OPTIONAL: "OPTIONAL",
  },
  ATTENDEE_RESPONSE: {
    NEEDS_ACTION: "NEEDS_ACTION",
    ACCEPTED: "ACCEPTED",
    DECLINED: "DECLINED",
    TENTATIVE: "TENTATIVE",
  },
  REMINDER_TYPE: {
    MINUTES_BEFORE: "MINUTES_BEFORE",
    AT_TIME: "AT_TIME",
  },
  REMINDER_CHANNEL: {
    IN_APP: "IN_APP",
    PUSH: "PUSH",
    EMAIL: "EMAIL",
  },
  NOTIFICATION_KIND: {
    EVENT_REMINDER: "EVENT_REMINDER",
    INVITE: "INVITE",
    SYSTEM: "SYSTEM",
  },
  THEME: {
    LIGHT: "LIGHT",
    DARK: "DARK",
    SYSTEM: "SYSTEM",
  },
  AUDIT_ACTION: {
    CREATE: "CREATE",
    UPDATE: "UPDATE",
    DELETE: "DELETE",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    VIEW: "VIEW",
    OTHER: "OTHER",
  },
};

// Default values
export const DEFAULTS = {
  TIMEZONE: "America/Mexico_City",
  DATE_FORMAT: "DD/MM/YYYY",
  TIME_FORMAT: "24h",
  WEEK_STARTS_ON: 1, // Monday
  DEFAULT_REMINDER_MINUTES: 15,
  CALENDAR_COLOR: "22d3ee", // cyan-400
  LANGUAGE: "es",
};

// Query keys for React Query
export const QUERY_KEYS = {
  PROFILE: "profile",
  GROUPS: "groups",
  GROUP_MEMBERS: "groupMembers",
  GROUP_INVITATIONS: "groupInvitations",
  CALENDARS: "calendars",
  EVENTS: "events",
  EVENT_ATTENDEES: "eventAttendees",
  NOTIFICATIONS: "notifications",
  USER_SETTINGS: "userSettings",
};
