#!/bin/bash

# Script para obtener el VAPID Key de Firebase
# Este script muestra las instrucciones para configurar Firebase Cloud Messaging

echo "================================================"
echo "  Firebase Cloud Messaging - Configuración"
echo "================================================"
echo ""
echo "Para obtener tu VAPID Key, sigue estos pasos:"
echo ""
echo "1. Abre Firebase Console:"
echo "   https://console.firebase.google.com"
echo ""
echo "2. Selecciona tu proyecto: agendapro-cbcd2"
echo ""
echo "3. Ve a Project Settings (⚙️ > Project settings)"
echo ""
echo "4. Selecciona la pestaña 'Cloud Messaging'"
echo ""
echo "5. Baja hasta 'Web Push certificates'"
echo ""
echo "6. Si no existe un Key Pair:"
echo "   - Haz clic en 'Generate key pair'"
echo "   - Espera a que se genere"
echo ""
echo "7. Copia el valor que comienza con 'B...'"
echo "   (debería verse algo como: BNxxxxxx...)"
echo ""
echo "8. Pega ese valor en el archivo .env:"
echo "   VITE_FIREBASE_VAPID_KEY=TU_VAPID_KEY_AQUI"
echo ""
echo "9. Reinicia el servidor de desarrollo:"
echo "   npm run dev"
echo ""
echo "================================================"
echo "  ¡Listo! 🎉"
echo "================================================"
echo ""
echo "Una vez configurado, las notificaciones push"
echo "funcionarán automáticamente en tu PWA."
echo ""
